version: "3"
services:
  app:
    # build:
    #   context: .
    # tty: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # volumes:
    #   - ./:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    command: sh -c "npm start"
    ports:
      - "3000:3000"
