version: "3"
services:
  app:
    build:
      context: .
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
